### ISSUE TITLE
I cannot find the plugin anywhere to download and use

### ISSUE THREAD

**Issue by ade90036** [newnewcoder/jboss-curl-deploy-gradle-plugin#1]
It is not in:
1)  maven, 
2)  bintray https://plugins.gradle.org/m2/com/github/newnewcoder 
3) https://jcenter.bintray.com/com/github/newnewcoder

I've manually built it now, but you should make sure you have it fully published.

**Comment by ade90036** [comment]
build it manually and adding to my build doesn't work..

It doesn't find the plugin.

The jar contains: com/github/newnewcoder/jbosscurl/ ??

**Comment by newnewcoder** [comment]
Thanks for your suggestion, I'll try to publish to jcenter or maven.

Before that, if you build this project manually, you can install this to local repository:

~~~bash
git clone https://github.com/newnewcoder/jboss-curl-deploy-gradle-plugin.git
cd jboss-curl-deploy-gradle-plugin
./gradlew install
~~~

and then add `buildscript` block to build.gradle like :

~~~groovy
buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
    }
    dependencies {
        //remove "gradle.plugin."
        classpath 'com.github.newnewcoder:jboss-curl-deploy-gradle-plugin:1.0.0-SNAPSHOT'
    }
}
apply plugin: 'com.github.newnewcoder.jboss-curl-deploy-gradle-plugin'
~~~

try deploy war to Jboss (jboss block in build.gradle must be set beforehand.)

~~~bash
gradlew deploy
~~~

**2017-05-21 update**

**Comment by newnewcoder** [comment]
Now it is available in jcenter, 

you can download from [https://jcenter.bintray.com/com/github/newnewcoder/](https://jcenter.bintray.com/com/github/newnewcoder/jboss-curl-deploy-gradle-plugin/) 

or just use it in `build.gradle`:

~~~groovy
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.github.newnewcoder:jboss-curl-deploy-gradle-plugin:1.0.0'
    }
}
apply plugin: 'com.github.newnewcoder.jboss-curl-deploy-gradle-plugin'
jboss {
    //. . .
}
~~~

For more example please refer to this [project's build.gradle](https://github.com/newnewcoder/jenkins-with-dapper-demo/blob/master/build.gradle)

**Comment by ade90036** [comment]
thanks... 👍

**Comment by newnewcoder** [comment]
Hope it helps. I will close this issue but feel free to reopen it if there is any problem.
